"""empty message

Revision ID: 2fd7cb93859c
Revises: 
Create Date: 2026-03-25 09:50:15.330034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd7cb93859c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acteur', schema=None) as batch_op:
        batch_op.alter_column('voornaam',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('achternaam',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('regisseur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('release_datum',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('trailer_url',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('regisseur', schema=None) as batch_op:
        batch_op.alter_column('voornaam',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('achternaam',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.alter_column('acteur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personage',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.alter_column('personage',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('acteur_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('regisseur', schema=None) as batch_op:
        batch_op.alter_column('achternaam',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('voornaam',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('trailer_url',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('release_datum',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('regisseur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('acteur', schema=None) as batch_op:
        batch_op.alter_column('achternaam',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('voornaam',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
