"""empty message

Revision ID: 676cdb404d58
Revises: 
Create Date: 2026-04-15 20:42:01.165228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676cdb404d58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.Text(), nullable=False),
    sa.Column('achternaam', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regisseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.Text(), nullable=False),
    sa.Column('achternaam', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('wachtwoord', sa.Text(), nullable=False),
    sa.Column('geboortedatum', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_favorite_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'film_id'),
    info={'is_view': True}
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('regisseur_id', sa.Integer(), nullable=False),
    sa.Column('release_datum', sa.Date(), nullable=False),
    sa.Column('trailer_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['regisseur_id'], ['regisseur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'film_id', name='uix_user_film')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acteur_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('personage', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['acteur_id'], ['acteur.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol')
    op.drop_table('rating')
    op.drop_table('favorite')
    op.drop_table('film')
    op.drop_table('user_favorite_ratings')
    op.drop_table('user')
    op.drop_table('regisseur')
    op.drop_table('acteur')
    # ### end Alembic commands ###
