"""empty message

Revision ID: d1b2c60525c9
Revises: b80ecae7bfa2
Create Date: 2026-03-30 22:35:02.827570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b2c60525c9'
down_revision = 'b80ecae7bfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'film_id', name='uix_user_film')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('geboortedatum',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('geboortedatum',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.drop_table('favorite')
    # ### end Alembic commands ###
